// megafunction wizard: %ALTINT_OSC%VBB%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTINT_OSC 

// ============================================================
// File Name: InternalClock.v
// Megafunction Name(s):
// 			ALTINT_OSC
//
// Simulation Library Files(s):
// 			cycloneiii
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.1.4 Build 182 03/12/2014 SJ Web Edition
// ************************************************************

//Copyright (C) 1991-2014 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.

module InternalClock (
	oscena,
	clkout)/* synthesis synthesis_clearbox = 1 */;

	input	  oscena;
	output	  clkout;

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: USED_PORT: clkout 0 0 0 0 OUTPUT NODEFVAL "clkout"
// Retrieval info: USED_PORT: oscena 0 0 0 0 INPUT NODEFVAL "oscena"
// Retrieval info: CONNECT: @oscena 0 0 0 0 oscena 0 0 0 0
// Retrieval info: CONNECT: clkout 0 0 0 0 @clkout 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock_bb.v TRUE
// Retrieval info: LIB_FILE: cycloneiii
