// SourceAndProbe.v

// Generated using ACDS version 13.1 182 at 2022.09.20.17:34:35

`timescale 1 ps / 1 ps
module SourceAndProbe (
	);

	SourceAndProbe_in_system_sources_probes_0 in_system_sources_probes_0 (
	);

endmodule
