// TinyChipScope.v

// Generated using ACDS version 13.1 182 at 2022.09.20.17:34:34

`timescale 1 ps / 1 ps
module TinyChipScope (
	);

	TinyChipScope_signaltap_ii_logic_analyzer_0 signaltap_ii_logic_analyzer_0 (
	);

endmodule
