// megafunction wizard: %ALTINT_OSC%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: ALTINT_OSC 

// ============================================================
// File Name: InternalClock.v
// Megafunction Name(s):
// 			ALTINT_OSC
//
// Simulation Library Files(s):
// 			cycloneiii
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 13.1.4 Build 182 03/12/2014 SJ Web Edition
// ************************************************************


//Copyright (C) 1991-2014 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, Altera MegaCore Function License 
//Agreement, or other applicable license agreement, including, 
//without limitation, that your use is for the sole purpose of 
//programming logic devices manufactured by Altera and sold by 
//Altera or its authorized distributors.  Please refer to the 
//applicable agreement for further details.


//altint_osc CBX_AUTO_BLACKBOX="ALL" DEVICE_FAMILY="Cyclone III" clkout oscena
//VERSION_BEGIN 13.1 cbx_altint_osc 2014:03:12:18:15:29:SJ cbx_arriav 2014:03:12:18:15:29:SJ cbx_cycloneii 2014:03:12:18:15:29:SJ cbx_lpm_add_sub 2014:03:12:18:15:29:SJ cbx_lpm_compare 2014:03:12:18:15:29:SJ cbx_lpm_counter 2014:03:12:18:15:29:SJ cbx_lpm_decode 2014:03:12:18:15:29:SJ cbx_mgl 2014:03:12:18:25:18:SJ cbx_nightfury 2014:03:12:18:15:23:SJ cbx_stratix 2014:03:12:18:15:31:SJ cbx_stratixii 2014:03:12:18:15:31:SJ cbx_stratixiii 2014:03:12:18:15:32:SJ cbx_stratixv 2014:03:12:18:15:32:SJ cbx_tgx 2014:03:12:18:15:29:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = cycloneiii_oscillator 1 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  InternalClock_altint_osc_947
	( 
	clkout,
	oscena) ;
	output   clkout;
	input   oscena;

	wire  wire_cycloneiii_oscillator1_clkout;

	cycloneiii_oscillator   cycloneiii_oscillator1
	( 
	.clkout(wire_cycloneiii_oscillator1_clkout),
	.oscena(oscena));
	assign
		clkout = wire_cycloneiii_oscillator1_clkout;
endmodule //InternalClock_altint_osc_947
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module InternalClock (
	oscena,
	clkout);

	input	  oscena;
	output	  clkout;

	wire  sub_wire0;
	wire  clkout = sub_wire0;

	InternalClock_altint_osc_947	InternalClock_altint_osc_947_component (
				.oscena (oscena),
				.clkout (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone III"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: USED_PORT: clkout 0 0 0 0 OUTPUT NODEFVAL "clkout"
// Retrieval info: USED_PORT: oscena 0 0 0 0 INPUT NODEFVAL "oscena"
// Retrieval info: CONNECT: @oscena 0 0 0 0 oscena 0 0 0 0
// Retrieval info: CONNECT: clkout 0 0 0 0 @clkout 0 0 0 0
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock.bsf FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL InternalClock_bb.v TRUE
// Retrieval info: LIB_FILE: cycloneiii
